### ISSUE TITLE
After update RouterOS to 6.45.1 api login don't work any more.

### ISSUE THREAD

**Issue by bonsi001** [mrin/domoticz-routeros-plugin#4]
Hi,

After update my RouterOs to v6.45.1 the api login from Domoticz won't work any more.
"login failure for user api from 192.168.10.20 via api".
I read at https://wiki.mikrotik.com/wiki/Manual:API#Initial_login that the login for api is changed.
Can anybody help to fix the issue on Domoticz ?

**Comment by StKob** [comment]
@bonsi001
I changed method of authorization. I'm not fully sure if this will work 100% correctly. You can find it on my fork and I also made pull request to this repo.

**Comment by mrin** [comment]
Hey guys,
I've merged update. Seems OK.
I'm not using domoticz anymore, so I can't test it, but as I looked at the updated doc - should be all ok with that change.
Thanks.

**Comment by bonsi001** [comment]
Hi all,

I have test the solution, it works very well.

Thanks
