### ISSUE TITLE
Does not work for routeros 6.45.1.

### ISSUE THREAD

**Issue by seansco** [mrin/domoticz-routeros-plugin#6]
api login method does not work in router os version 6.45.1 and above
https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

**Comment by Shaheding** [comment]
It's right. This plugin cannot login into RouterOS anymore.
You have to implement the new method.

**Comment by Bartekn86** [comment]
could you update plugin pleas ?

**Comment by mrin** [comment]
I'm not using Domoticz anymore, but I've just installed it in VM and tested plugin and it works. 
Domoticz 2020.2 12723
RouterOS 6.47.7 (stable)
